# Generated by Django 6.0.3 on 2026-03-29 03:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reference_number', models.CharField(blank=True, max_length=20, unique=True)),
                ('language', models.CharField(choices=[('zulu', 'Zulu'), ('xhosa', 'Xhosa'), ('sotho', 'Sotho'), ('afrikaans', 'Afrikaans'), ('english', 'English'), ('tswana', 'Tswana')], default='english', max_length=20)),
                ('mode', models.CharField(choices=[('standard', 'Standard Mode'), ('simplified', 'Simplified Mode')], default='standard', max_length=20)),
                ('issue_type', models.CharField(choices=[('pothole', 'Pothole'), ('water_leak', 'Water Leak'), ('waste', 'Uncollected Waste'), ('electricity', 'Electricity Outage'), ('other', 'Other')], max_length=50)),
                ('address', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('phone_number', models.CharField(max_length=15)),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(default='Received', max_length=50)),
            ],
        ),
    ]
