# Generated by Django 6.0.3 on 2026-03-29 20:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reporting', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='report',
            name='language',
            field=models.CharField(choices=[('zulu', 'Zulu'), ('xhosa', 'Xhosa'), ('sotho', 'Sotho'), ('afrikaans', 'Afrikaans'), ('english', 'English')], default='english', max_length=20),
        ),
        migrations.AlterField(
            model_name='report',
            name='status',
            field=models.CharField(choices=[('Received', 'Received'), ('Under Review', 'Under Review'), ('In Progress', 'In Progress'), ('Resolved', 'Resolved')], default='Received', max_length=50),
        ),
    ]
